### ISSUE TITLE
after call stopAudioDeviceLoopbackTest, the totalVolume of onAudioVolumeIndication  is always 0.

### ISSUE THREAD

**Issue by SuperShan0926** [AgoraIO-Extensions/Electron-SDK#1052]
mac os agorasdk 4.1.1rc1 

加入频道后想测试本地麦克风，调用startAudioDeviceLoopbackTest 和 stopAudioDeviceLoopbackTest 去测试，测完之后onAudioVolumeIndication 里的回调里的 totalVolume 就都变成 0 了，这里bug还是需要调用别的api重新做什么设置吗？

<img width="810" alt="image" src="https://github.com/AgoraIO-Extensions/Electron-SDK/assets/19642899/0f97598e-a381-4d9b-b3ad-03d24df879d3">

**Comment by LichKing-2234** [comment]
请问测完之后onAudioVolumeIndication是指什么，调用了stopAudioDeviceLoopbackTest？

**Comment by LichKing-2234** [comment]
我这边测试，是可以的
<img width="236" alt="image" src="https://github.com/AgoraIO-Extensions/Electron-SDK/assets/9312526/c778c56a-89e5-4881-bc86-59693b5c0431">
