### ISSUE TITLE
日志文件格式由文本改成二进制了吗?

### ISSUE THREAD

**Issue by lvxiaohai** [AgoraIO-Extensions/Electron-SDK#1163]
如题4.3.0版本日志文件有文本格式改成二进制了吗?

```javascript
const rtcEngine = createAgoraRtcEngine();
rtcEngine.initialize({
  appId: 'xxx',
  logConfig: { filePath: 'agora-sdk.log' },
});

```

agora-sdk.log文件在4.3.0之前是文本格式,4.3.0之后是二进制格式无法查看
<img width="678" alt="image" src="https://github.com/AgoraIO-Extensions/Electron-SDK/assets/2291134/794aaed2-1cc8-4929-9f1f-a228c0de16b4">

**Comment by guoxianzhe** [comment]
@lvxiaohai 430版本开始不会提供明文SDK的详细日志,您可以根据自己的业务需要,参考明文的SDK API日志来调查API的调用情况,以及在回调中查看回调调用情况。
如果有特殊需要,可通过工单形式获取解密日志。

**Comment by lvxiaohai** [comment]
> @lvxiaohai 430版本开始不会提供明文SDK的详细日志,您可以根据自己的业务需要,参考明文的SDK API日志来调查API的调用情况,以及在回调中查看回调调用情况。 如果有特殊需要,可通过工单形式获取解密日志。

因为在使用sdk中出了问题才去查日志的,如果不是明文查起来更困难了
