### ISSUE TITLE
Remove unnesseray dependencies!

### ISSUE THREAD

**Issue by henrydf** [AgoraIO-Extensions/Electron-SDK#1182]
**Is your feature request related to a problem? Please describe.**
Why this SDK requires some annoying things such as `gulp*` and `ts-interface-checker` in production dependencies?

**Describe the solution you'd like**
Keep production dependencies clear.

**Describe alternatives you've considered**
Or provide some pre-bundled version in dist or somewhere.

**Additional context**
Current dependencies make bundle result mess.

**Comment by guoxianzhe** [comment]
@henrydf Thanks for your advice!
Currently, **gulp** is necessary, this will download our c++ native modules when you install Electron-SDK.
**ts-interface-checker** is necessary when we check some variables in runtime.

If you have any suggestions please leave a message.

**Comment by henrydf** [comment]
How about provide a prebuild version of js/ts files. Then I just need to bundle the prebuild result instead of 500+ dependencies.

**Comment by guoxianzhe** [comment]
@henrydf The main reason for this problem is gulp IMO. Maybe We can remove gulp in the future. I will talk with my team and make it happen in the feature. This gonna be a huge work to do and please wait my further progress.

**Comment by henrydf** [comment]
Glad to see it.
