### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by keenoptical** [AgoraIO-Extensions/Electron-SDK#1229]
I've got an error trying to install package with npm. 
<img width="1105" alt="231123123" src="https://github.com/user-attachments/assets/8cedf18a-7135-4f0c-aa41-437a58bb5bb5">

Then i've tried to use pnpm but error still remaining.
<img width="1920" alt="35434535" src="https://github.com/user-attachments/assets/6986ee0a-3dd0-4d83-8f34-b315da081627">

Node.js version 20.18.0
Npm version 10.8.2
Pnpm version 8.15.5

Also tried to use node.js version 18.20.4 but it caused no results.

**Comment by guoxianzhe** [comment]
@keenoptical There are two options you can do:

1. use yarn
2. set [COREPACK_ENABLE_AUTO_PIN](https://github.com/nodejs/corepack/blob/main/README.md#environment-variables) to 0 in your environment to disable this behavior

I will remove this limit in the feature version

**Comment by keenoptical** [comment]
Tnanks! After including yarn everythings setups correctly.
