### ISSUE TITLE
Could not resolve "../build/Release/agora_node_ext"

### ISSUE THREAD

**Issue by devmalcolm** [AgoraIO-Extensions/Electron-SDK#1240]
I'm trying to install the Agora Electron SDK on my Mac (ARM) and integrate it with my Electron + Vite app wich also using react. However, as soon as I import the SDK and initialize it using my AppID, it throws an error.

`Could not resolve "../build/Release/agora_node_ext"`

<img width="452" alt="Screenshot 2024-11-06 at 11 42 09" src="https://github.com/user-attachments/assets/34786f6a-4ba2-4456-8eb1-a5b3e9e2cdbf">

After some research, I saw that others mentioned this issue might be related to Vite's compatibility with the Electron SDK. To troubleshoot, I tried using the Agora React SDK instead, which worked well but caused a codec error, likely due to browser compatibility issues. Because of this, I'm returning to the Electron SDK and looking for a way to resolve the initial error.

Currently, I’m running the app in development mode via `npm run dev`, so I'm not building it yet, which I assume shouldn't cause issues. Any insights into getting the Agora Electron SDK to work with Vite or troubleshooting the initialization error would be appreciated!

**Concerning dep. versions im using:**
`"electron": "^29.1.4"`
`"vite": "^5.1.6"`
`"vite-plugin-electron": "^0.28.4"`
`"vite-plugin-electron-renderer": "^0.14.5"`
`"agora-electron-sdk": "^4.4.0"`
`"react": "^18.2.0"`

Code that throw the error:

```js
import createAgoraRtcEngine from "agora-electron-sdk";

const rtcEngine = createAgoraRtcEngine();
rtcEngine.initialize({appId: "AppID"});
```

**Comment by guoxianzhe** [comment]
@devmalcolm Check this https://electron-vite.github.io/guide/cpp-addons.html

**Comment by showtan001** [comment]
> @devmalcolm Check this https://electron-vite.github.io/guide/cpp-addons.html

文档给的2种方法都试过了，都不起作用，有成功的demo可以提供下吗？

**Comment by showtan001** [comment]
@guoxianzhe
