### ISSUE TITLE
installation script should not depend yarn

### ISSUE THREAD

**Issue by cuishuo0102** [AgoraIO-Extensions/Electron-SDK#1242]
**Describe the bug**
npm install calls yarn, and an error fired if yarn is not installed

**To Reproduce**
1. npm install agora-electron-sdk
2. see error

npm verbose pkgid agora-electron-sdk@4.4.0
npm error code 127
npm error path /Users/<user>/<project>/node_modules/agora-electron-sdk
npm error command failed
npm error command sh -c yarn checkElectron
npm error sh: yarn: command not found
npm verbose cwd /Users/<user>/<project>
npm verbose os Darwin 23.6.0
npm verbose node v20.16.0
npm verbose npm  v10.8.1
npm verbose exit 127
npm verbose code 127

**Expected behavior**
An npm install progress should not assume user has yarn installed

**Desktop (please complete the following information):**
 - OS: macOS 14.6

**Comment by guoxianzhe** [comment]
@cuishuo0102  Thanks for your issues. We already fix this in [4.5.0](https://github.com/AgoraIO-Extensions/Electron-SDK/pull/1228) , and you can use patch version [4.4.1-build.2-rc.1](https://www.npmjs.com/package/agora-electron-sdk/v/4.4.1-build.2-rc.1) to avoid this issue.
