### ISSUE TITLE
use offscreenCanvas to speed up performance?

### ISSUE THREAD

**Issue by Zaynex** [AgoraIO-Extensions/Electron-SDK#327]
The OffscreenCanvas interface provides a canvas that can be rendered off screen. It is available in both the window and worker contexts. (from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas))

We can go for it in electron.

Benefits:
1. Not block main thread 
2. Speed up performance by using web worker.

See someone's demo:  
https://blog.scottlogic.com/2020/03/19/offscreen-canvas.html

Maybe can help with this issue #14

**Comment by plutoless** [comment]
thanks for the suggestion. very inspiring.
However currently the performance issue mainly happens between c++ layer -> js layer. I think what this solution can really solve is to unblock main thread, while for performance it will not help too much as the updated flow would be c++ -> js -> web worker. 
i can still try to implement a custom render using this approach sometime when i have time though. are you suffering from performance issue now?

**Comment by Zaynex** [comment]
Currently, no.  I have sat low fps and dimension. 
We can't cut down the c++ to js layer performace, so I just focus on js .

By the way, yuv-canvas support webgl. Why not just use it  as GIRender?
