### ISSUE TITLE
App Store Submission | App Rejection

### ISSUE THREAD

**Issue by silarvaibhav** [AgoraIO-Extensions/Electron-SDK#406]
Though its more a electron thing, but still like to highlight as support of Agora is restricted to  electron 7.1.2 version:

My app was rejected yesterday stating below reason:
Your app uses or references the following non-public APIs:

• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSURLFileTypeMappings
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/CAContext
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSAccessibilityRemoteUIElement
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSNextStepFrame
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSThemeFrame
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/CALayerHost

The use of non-public APIs is not permitted on the App Store, because it can lead to a poor user experience should these APIs change.

Now we cannot upgrade the electron version, due to agora requirements.

In this case, what is the best possible solution to submit app in App store?

Thanks in advance

**Comment by plutoless** [comment]
it's a known issue: https://github.com/electron/electron/issues/20027
it's fixed starting from 8.0.2 and 9.0.0-beta.3 https://github.com/electron/electron/pull/22354
Maybe you will need to upgrade your electron version

**Comment by uffou** [comment]
I have the same issue Electron 12.0.2
Should I downgrade to Electron 9?

Your app links against the following non-public framework(s):

• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/CAContext
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSAccessibilityRemoteUIElement
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSNextStepFrame
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSThemeFrame
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/CALayerHost
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSAppendToKillRing
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AudioDeviceDuck
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionProductVersionExtraKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionProductVersionExtraKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetBytePtr
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_CTFontDescriptorIsSystemUIFont
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSYankFromKillRing
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSInitializeKillRing
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__CFCopySystemVersionDictionary
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__CFCopySystemVersionDictionary
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCopyEndMarker
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_CGFontRenderingGetFontSmoothingDisabled
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionProductNameKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionProductNameKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCopyStartMarker
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSNewKillRingSequence
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_IOBluetoothPreferenceSetControllerPowerState
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__CFCopyServerVersionDictionary
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__CFCopyServerVersionDictionary
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__LSSetApplicationLaunchServicesServerConnectionStatus
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionProductVersionKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionProductVersionKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionBuildVersionKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionBuildVersionKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerCreate
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_NSTextInputReplacementRangeAttributeName
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeGetTypeID
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetLength
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCreate
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_SetApplicationIsDaemon
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSSetKillRingToYankedState
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetTypeID

**Comment by Foxhoundn** [comment]
> I have the same issue Electron 12.0.2
> 
> Should I downgrade to Electron 9?
> 
> 
> 
> Your app links against the following non-public framework(s):
> 
> 
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/CAContext
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSAccessibilityRemoteUIElement
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSNextStepFrame
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSThemeFrame
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/CALayerHost
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSAppendToKillRing
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AudioDeviceDuck
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionProductVersionExtraKey
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionProductVersionExtraKey
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetBytePtr
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_CTFontDescriptorIsSystemUIFont
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSYankFromKillRing
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSInitializeKillRing
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__CFCopySystemVersionDictionary
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__CFCopySystemVersionDictionary
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCopyEndMarker
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_CGFontRenderingGetFontSmoothingDisabled
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionProductNameKey
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionProductNameKey
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCopyStartMarker
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSNewKillRingSequence
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_IOBluetoothPreferenceSetControllerPowerState
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__CFCopyServerVersionDictionary
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__CFCopyServerVersionDictionary
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__LSSetApplicationLaunchServicesServerConnectionStatus
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionProductVersionKey
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionProductVersionKey
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionBuildVersionKey
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionBuildVersionKey
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerCreate
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_NSTextInputReplacementRangeAttributeName
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeGetTypeID
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetLength
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCreate
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_SetApplicationIsDaemon
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSSetKillRingToYankedState
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetTypeID

Exactly the same issue for me, my app got rejected 10 mins ago with the same messagge.

Any ideas?

**Comment by Foxhoundn** [comment]
> I have the same issue Electron 12.0.2
> Should I downgrade to Electron 9?
> 
> Your app links against the following non-public framework(s):
> 
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/CAContext
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSAccessibilityRemoteUIElement
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSNextStepFrame
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSThemeFrame
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/CALayerHost
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSAppendToKillRing
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AudioDeviceDuck
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionProductVersionExtraKey
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionProductVersionExtraKey
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetBytePtr
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_CTFontDescriptorIsSystemUIFont
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSYankFromKillRing
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSInitializeKillRing
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__CFCopySystemVersionDictionary
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__CFCopySystemVersionDictionary
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCopyEndMarker
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_CGFontRenderingGetFontSmoothingDisabled
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionProductNameKey
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionProductNameKey
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCopyStartMarker
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSNewKillRingSequence
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_IOBluetoothPreferenceSetControllerPowerState
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__CFCopyServerVersionDictionary
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__CFCopyServerVersionDictionary
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__LSSetApplicationLaunchServicesServerConnectionStatus
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionProductVersionKey
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionProductVersionKey
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionBuildVersionKey
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionBuildVersionKey
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerCreate
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_NSTextInputReplacementRangeAttributeName
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeGetTypeID
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetLength
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCreate
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_SetApplicationIsDaemon
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSSetKillRingToYankedState
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetTypeID

The `electron` repo has a template for new issues regarding MAS rejection, so I would suggest You also open an issue there (I did already) - the more issues opened the more traction.
