### ISSUE TITLE
屏幕共享区域偏移

### ISSUE THREAD

**Issue by wning13** [AgoraIO-Extensions/Electron-SDK#789]
使用videoSourceStartScreenCaptureByDisplayId/videoSourceStartScreenCaptureByScreen分享屏幕区域，并设置excludeWindowList时，预览画面发生了偏移
预览画面的x和y是设置的2倍，右边和下边分别有宽高为x，y的黑边，鼠标位置未偏移
如果excludeWindowList传空数组则画面正常

agora-electron-sdk: 3.7.0-build.527
electron: 12.2.3
os: macOS Big Sur 11.6

**Comment by zhangtao1104** [comment]
帮忙把接口调用的参数设置发下，我们确认下能否复现这个问题。

**Comment by wning13** [comment]
> 帮忙把接口调用的参数设置发下，我们确认下能否复现这个问题。
![企业微信截图_844420b8-39a8-437a-96b0-003c3aa652cd](https://user-images.githubusercontent.com/7438062/177072156-d866b65e-aaf7-4fcf-bb4f-36c6c4283958.png)

**Comment by wning13** [comment]
另外，当rect的width大于param的width时，即使不设置excludeWindowList也会发生异常的偏移，导致画面无法完整显示

**Comment by RoJoHub** [comment]
> 另外，当rect的width大于param的width，且x，y不为0时，即使不设置excludeWindowList也会发生异常的偏移，导致画面无法完整显示
我们已经复现该问题, 正在积极修复.

**Comment by wning13** [comment]
@RoJoHub 还有一个问题，window平台接多个显示器，如果第一个显示器（id为0）不是主显示器，videoSourceStartScreenCaptureByDisplayId传入displayId为{id: 0}时，实际捕捉的是主显示器，而不是选择的显示器

**Comment by RoJoHub** [comment]
请根据 getScreenCaptureSource的primaryMonitor字段来判断是否主显示器

**Comment by wning13** [comment]
> 请根据 getScreenCaptureSource的primaryMonitor字段来判断是否主显示器

我知道如何判断主显示器，现在的问题是这个场景下实际捕捉的显示器不是预期的显示器

**Comment by zhangtao1104** [comment]
getScreenCaptureSource 里的 sourceId 吗？

**Comment by wning13** [comment]
> getScreenCaptureSource 里的 sourceId 吗？

是的
