### ISSUE TITLE
rtcEngine.initialize为undefined

### ISSUE THREAD

**Issue by woshixiaoqianbi** [AgoraIO-Extensions/Electron-SDK#895]
electron ：8.5.5
agora-electron-sdk: ^4.0.0
`javascript`
    initAgora() {
      const AgoraRtcEngine = require('agora-electron-sdk').default
      const os = require('os')
      const path = require('path')

      // 填入你的 App ID
      const APPID = "5000783d60744b429d0f53ef962577bc"
      // 填入你的 Token
      this.token = "007eJxTYMjfwrX6TZkZi8z+VmazRpZnPoXRUbmmEjPD3RR2r7pulaHAYGpgYGBuYZxiZmBuYpJkYmSZYpBmapyaZmlmZGpunpRs88Y5ea+ta7IFlzsjIwMEgvicDMnZ2YaWliaGFgwMAM/zHUI="

      const sdkLogPath = path.resolve(os.homedir(), "./test.log")

      this.rtcEngine = new AgoraRtcEngine()
      console.log("rtcEngine", this.rtcEngine)
      // rtcEngine.on('error', (err, msg) => {
      //     console.log("Error!")
      // })

      // 视频模块默认开启，需要调用 disableVideo 关闭视频模块，才能开启纯语音模式
      this.rtcEngine.disableVideo()

      this.rtcEngine.setLogFile(sdkLogPath)

      this.rtcEngine.onJoinChannelSuccess = (connection, elapsed) => {
        console.log("rtcEngine.onJoinChannelSuccess", connection, elapsed)
      }

      this.rtcEngine.onLeaveChannel = (connection, stats) => {
        console.log("rtcEngine.onLeaveChannel", connection, stats)
      }

      this.rtcEngine.onError = (errCode, msg) => {
        console.log("rtcEngine.onError", errCode, msg)
      }

      this.rtcEngine.onRejoinChannelSuccess = (connection, elapsed) => {
        console.log("rtcEngine.onRejoinChannelSuccess", connection, elapsed)
      }

      // 初始化 AgoraRtcEngine 实例
      console.log(this.rtcEngine.initialize(APPID))
      // 填入的频道名必须与生成临时 Token 时填入的频道名一致

    },
    joinAgora() {
      // 加入频道
      console.log(this.rtcEngine.joinChannel(this.token, "ckk199418", null, 123456))
      console.log(this.rtcEngine.getConnectionState())
    },
    leaveAgora() {
      console.log(this.rtcEngine.leaveChannel(this.token, "ckk199418", null, 123456))
    }

**Comment by woshixiaoqianbi** [comment]
![微信图片_20221010181812](https://user-images.githubusercontent.com/18699589/194845395-fe15bb22-380d-4a5a-a1f3-3c692c63063c.png)
![微信图片_20221010181805](https://user-images.githubusercontent.com/18699589/194845405-0898b702-0ee4-4852-8474-4882e2a0275e.png)

**Comment by woshixiaoqianbi** [comment]
好的，谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月10日 18:45 |
| 收件人 | ***@***.***> |
| 抄送至 | QianBi ***@***.******@***.***> |
| 主题 | Re: [AgoraIO-Extensions/Electron-SDK] rtcEngine.initialize为undefined (Issue #895) |

你4.0的调用方式不对，可以参考repo的example目录

或者我们4.0的文档：https://docs.agora.io/cn/video-call-4.x/start_call_electron_ng?platform=Electron

**Comment by luz33c** [comment]
想了解你的代码为什么这么写？是看的老的文档吗？

**Comment by woshixiaoqianbi** [comment]
> 想了解你的代码为什么这么写？是看的老的文档吗？

我是新建了一个项目，然后右边的quick start选中了electron，里面的示例代码是我上面写的代码

**Comment by woshixiaoqianbi** [comment]
![微信图片_20221011112539](https://user-images.githubusercontent.com/18699589/194990266-1c7250f2-505d-4c54-906a-d01d3e43ace3.png)
对了，依赖库里的这个node文件可以把后缀补齐么，demo里面没问题，但是集成到自己项目里就require识别不到了

**Comment by plutoless** [comment]
看起来问题解决了，如果还有问题可以reopen
