### ISSUE TITLE
Vite 构建项目报错

### ISSUE THREAD

**Issue by oyjt** [AgoraIO-Extensions/Electron-SDK#928]
直接集成SDK没问题，采用Vite构建的项目集成就会报下面的错误。
```
[ERROR] Could not resolve "../../../build/Release/agora_node_ext"

    node_modules/agora-electron-sdk/js/Private/internal/IrisApiEngine.js:15:22:
      15 │ const agora = require('../../../build/Release/agora_node_ext');
         ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

SDK版本：4.0.1-rc.2
Vite版本：3.2.2
Electron版本：21.1.0

推测是Vite依赖预构建造成的问题。所以想问Vite集成SDK有好的的解决方案吗？

最后用`vite-plugin-resolve`解决这一问题，分享出来以避免大家采坑。

大家有好的解决方案也可以分享一下。

**Comment by denglouhen** [comment]
大佬能详细说一下vite-plugin-resolve怎么解决的吗？

**Comment by oyjt** [comment]
> 大佬能详细说一下vite-plugin-resolve怎么解决的吗？
`vite-plugin-resolve`插件的具体使用方式，参考[官方文档](https://github.com/vite-plugin/vite-plugin-resolve)

**Comment by denglouhen** [comment]
> > 大佬能详细说一下vite-plugin-resolve怎么解决的吗？
> > `vite-plugin-resolve`插件的具体使用方式，参考[官方文档](https://github.com/vite-plugin/vite-plugin-resolve)

话说你的项目能正常joinChannel吗？我成功import sdk后实例化，joinChannel没有任何反应。

**Comment by oyjt** [comment]
> 话说你的项目能正常joinChannel吗？我成功import sdk后实例化，joinChannel没有任何反应。

我的可以正常使用。你有没有报啥错？

**Comment by denglouhen** [comment]
> > 话说你的项目能正常joinChannel吗？我成功import sdk后实例化，joinChannel没有任何反应。
> 
> 我的可以正常使用。你有没有报啥错？

你是vue还是react还是anular写的？

**Comment by oyjt** [comment]
vue3写的

**Comment by denglouhen** [comment]
> vue3写的

大佬能不能求一份demo啊，我想知道自己到底是哪里不对一直跑不起来。知道可能很麻烦，但真的希望大佬可以发我看一下。597073407@qq.com。

**Comment by oyjt** [comment]
> 大佬能不能求一份demo啊，我想知道自己到底是哪里不对一直跑不起来。知道可能很麻烦，但真的希望大佬可以发我看一下。[597073407@qq.com](mailto:597073407@qq.com)。

写demo麻烦，我贴一下最简化代码，你参考看看：
```
const agoraEngine = createAgoraRtcEngine();
  agoraEngine.initialize({ appId: agoraAppId }); // 填入声网appId
  // 注册事件监听
  // agoraEngine.registerEventHandler(EventHandles);
  // 设置频道场景，1表示多用户场景
  agoraEngine.setChannelProfile(ChannelProfileType.ChannelProfileLiveBroadcasting);  // 值为1
  // 设置用户角色为主播，1表示主播，2表示听众
  agoraEngine.setClientRole(ClientRoleType.ClientRoleBroadcaster); //值为1

  const localVideoContainer = document.querySelector('#VideoAvatar');
  // 开启本地视图
  agoraEngine.setupLocalVideo({
    sourceType: 0,
    view: localVideoContainer,
  });

  // 开启视频模块
  agoraEngine.enableVideo();
  // 开启本地预览
  agoraEngine.startPreview();
  // 填入你的频道名。填入的频道名必须与生成临时 Token 时填入的频道名一致。
  // 加入频道
  const token ='xxxxxx'; // 你的临时token
  const channel = 'TestChannel'; // 你的频道名
  const uid = '123456789'; // 你的uid
  agoraEngine.joinChannel(token, channel, uid);
 ···

**Comment by denglouhen** [comment]
> agoraEngine.setClientRole(ClientRoleType.ClientRoleBroadcaster);

好的谢谢您。最后问一下，你的监听回调是怎么写的？ agoraEngine.addListener("onJoinChannelSuccess",()=>{xxxxx});这样吗？

**Comment by oyjt** [comment]
> agora-electron-sdk

// 注册事件监听
 agoraEngine.registerEventHandler(EventHandles);

**Comment by grguang** [comment]
> 
@oyjt 请问下，主播怎么开启的屏幕共享，然后听众怎么监听到主播开启了共享，然后怎么接收的共享画面，不知道你的场景有没有涉及到，能否详细说一下流程？

**Comment by oyjt** [comment]
> 请问下，主播怎么开启的屏幕共享，然后听众怎么监听到主播开启了共享，然后怎么接收的共享画面，不知道你的场景有没有涉及到，能否详细说一下流程？

这个可以看下官方的最新文档[https://docs.agora.io/en/video-calling/develop/product-workflow?platform=electron](https://docs.agora.io/en/video-calling/develop/product-workflow?platform=electron)

**Comment by 7mus1c** [comment]
> > 大佬能详细说一下vite-plugin-resolve怎么解决的吗？
> 
> `vite-plugin-resolve`插件的具体使用方式，参考[官方文档](https://github.com/vite-plugin/vite-plugin-resolve) 可以参考我下面的代码：
> 
> 插件配置示例代码：
> 
> ```
> import resolve from 'vite-plugin-resolve';
> export const ConfigResolvePlugin = () => {
>   return resolve({
>     'agora-electron-sdk': `
>       const { createAgoraRtcEngine } = require("agora-electron-sdk")
>       export {
>         createAgoraRtcEngine
>       }
>     `,
>   });
> };
> ```
> 
> 配置好后，项目中正常导入插件使用就行，代码如下：
> 
> ```
> import { createAgoraRtcEngine } from 'agora-electron-sdk';
> ```

大佬能问一下 vite的配置嘛？我这边一直显示 ReferenceError: require is not defined
希望能贴一份具体的配置给我

**Comment by oyjt** [comment]
> > > 大佬能详细说一下vite-plugin-resolve怎么解决的吗？
> > 
> > 
> > `vite-plugin-resolve`插件的具体使用方式，参考[官方文档](https://github.com/vite-plugin/vite-plugin-resolve) 可以参考我下面的代码：
> > 插件配置示例代码：
> > ```
> > import resolve from 'vite-plugin-resolve';
> > export const ConfigResolvePlugin = () => {
> >   return resolve({
> >     'agora-electron-sdk': `
> >       const { createAgoraRtcEngine } = require("agora-electron-sdk")
> >       export {
> >         createAgoraRtcEngine
> >       }
> >     `,
> >   });
> > };
> > ```
> > 
> > 
> > 配置好后，项目中正常导入插件使用就行，代码如下：
> > ```
> > import { createAgoraRtcEngine } from 'agora-electron-sdk';
> > ```
> 
> 大佬能问一下 vite的配置嘛？我这边一直显示 ReferenceError: require is not defined 希望能贴一份具体的配置给我

试试直接用`optimizeDeps.exclude`这个配置属性排除`agora-electron-sdk`的依赖预构建
